# Generated by Django 2.2.1 on 2019-05-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='type',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second')], default='first', max_length=10, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='publish',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
