# Generated by Django 2.2.1 on 2019-05-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190523_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='publish',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='publish',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='书的简介'),
        ),
    ]
