# Generated by Django 2.2.1 on 2019-05-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_publish_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='content',
            field=models.TextField(default='', verbose_name='书的内容'),
        ),
    ]
