# Generated by Django 2.2.1 on 2019-05-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_publish_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='书的内容'),
        ),
    ]
