# Generated by Django 2.2.1 on 2019-05-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_publish_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='catalogs',
            field=models.TextField(blank=True, null=True, verbose_name='书的目录'),
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='书的简介'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='书的名字'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='boss',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='老板名字'),
        ),
    ]
