# Generated by Django 2.2.1 on 2019-05-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190525_0808'),
        ('books', '0005_auto_20190525_0805'),
    ]

    operations = [
    ]
